spring:
  datasource:
    url: jdbc:mysql://localhost:55432/blog-db
    username: ezen
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate:
      SQL: DEBUG
      orm.jdbc.bind: TRACE
    your.package.name: DEBUG

minio:
  url: http://localhost:9000
  accessKey: ezen
  secretKey: password
  buckets:
    userProfile: user-profile-images
    postImage: post-images