spring:
  application:
    name: blog
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comment: true
        format_sql: true
        highlight_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

mybatis:
  mapper-locations: classpath:mapper/**/*.xml

jwt:
  secret: uz7MtIBd5PpX0knZuSB4RLlgFJ/v7ySsMofaMGZ1wec=
  expiration-time: 43200000  # 12 hours in milliseconds